const fs = require('fs')
const path = require('path')

const projectRoot = path.resolve(__dirname, '..')
const repoRoot = path.resolve(projectRoot, '..', '..')
const sourceRoot = repoRoot
const destRoot = path.join(projectRoot, 'public', 'tour')

const COPY_PATHS = ['index.html', 'css', 'js']
const WARNING_COMMENT = `<!-- AUTO-COPIED FROM CCP Project/ — do not edit this file directly.
     Make all edits in CCP Project/ then re-copy to public/tour/ -->`

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true })
}

function clearDir(dirPath) {
  if (!fs.existsSync(dirPath)) return
  for (const entry of fs.readdirSync(dirPath)) {
    fs.rmSync(path.join(dirPath, entry), { recursive: true, force: true })
  }
}

function copyFromSource() {
  ensureDir(destRoot)
  clearDir(destRoot)

  for (const relPath of COPY_PATHS) {
    const src = path.join(sourceRoot, relPath)
    const dst = path.join(destRoot, relPath)
    fs.cpSync(src, dst, { recursive: true, force: true })
  }
}

function injectWarningComment() {
  const indexPath = path.join(destRoot, 'index.html')
  const html = fs.readFileSync(indexPath, 'utf8')
  if (html.includes('AUTO-COPIED FROM CCP Project/')) return
  const updated = html.replace('<body>', `<body>\n  ${WARNING_COMMENT}`)
  fs.writeFileSync(indexPath, updated, 'utf8')
}

copyFromSource()
injectWarningComment()
console.log('Synced CCP Project tour files into public/tour/')
